config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "splash#index"

  resources :splash, only: [:index]
  resources :categories do
    resources :purchases
  end

  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :read, Splash
    return unless user.present?

    can :manage, Category, user: user
    can :manage, Purchase, user: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  attr_accessor :total

  belongs_to :user
  has_many :purchases
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'
  validates :amount, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  def index
    categories = Category.includes(:purchases).all
    @categories = categories.map do |category|
      category.total = category.purchases.where(author: current_user).sum(:amount)
      category
    end
  end

  def new
    @category = Category.new
  end

  def show; end

  def edit; end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was created successfully.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was updated successfully.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_purchase, only: %i[show edit update destroy]

  def index
    @purchases = Purchase.where(author: current_user, category_id: params[:category_id]).order(updated_at: :desc)
    @total = @purchases.sum(:amount)
  end

  def new
    @purchase = Purchase.new
    set_users_categories
  end

  def show; end

  def edit; end

  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.author = current_user
    respond_to do |format|
      if @purchase.save
        format.html do
          redirect_to category_purchases_url(category_id: @purchase.category_id),
                      notice: 'Purchase was successfully created.'
        end
        format.json { render :show, status: :created, location: @purchase }
      else
        set_users_categories
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to purchase_url(@purchase), notice: 'Purchase was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_users_categories
    @users = User.pluck(:name, :id)
    @categories = Category.pluck(:name, :id)
  end

  def destroy
    @purchase.destroy

    respond_to do |format|
      format.html { redirect_to purchases_url, notice: 'Purchase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_purchase
    @purchase = Purchase.find(params[:id])
  end

  def purchase_params
    params.require(:purchase).permit(:name, :amount, :category_id, :author_id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    redirect_to :categories if current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <div class="card my-1 shadow">
    <div class="container py-1 px-1">
      <div class="row">
        <div class="col-4">
          <%= image_tag "https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2432&q=80", alt: category.name, style: 'width: 100px; height: 100px;'%>
        </div>
          <div class="card-body col-6">
            <div class="card-text container">
            <div class="row">
                <div class="col-6 text-primary">
                  <h5 class="card-title">
                    <%=category.name%>
                  </h5>
                </div>
                <div class="col-6">
                  $<span><%=category.total%></span>
                </div>
                <div class="col-12 fw-lighter text-muted">
                  <span class><%=category.updated_at.strftime("%d %b %Y")%></span>
                </div>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>

</div>

app/views/categories/_error_messages.html.erb
<% if model.errors.any? %>
	<%model.errors.full_messages.each do |message|%>
		<p class='text-danger'><%=message%></p>
	<%end%>
<% end %>

app/views/categories/_form.html.erb
<div class="p-2">
<%= form_with(model: category) do |f| %>
    <div class=" b w-100 d-flex justify-content-between align-items-center bg-primary text-white">
      <%= link_to  categories_path, id: 'back_to_home' do %>
        <i class="fa fa-arrow-left text-white ms-4" aria-hidden="true"></i>
      <%end%>

      <p class="mb-0 p-4">New Category</p>
      <%= f.submit "Submit", class:'btn btn-sm me-4 btn-success rounded-1 text-white',data:{turbo:false} %>
    </div>
    <%=render 'error_messages', model: category %>

    <%= f.text_field :name, placeholder: 'name', class: 'form-control rounded-0 name' %>

    <%= f.select :icon, ['Toyota', 'Chevrolet', 'Marcedes', 'Volkswagen'], {}, {class: "form-control form-select"} %>

<% end %>
</div>

app/views/categories/_logout.html.erb
<%= button_to "logout", destroy_user_session_path,method: :delete, class: 'btn btn-block text-decoration-none mt-4 bg-warning text-white text-center' %>

app/views/categories/edit.html.erb
<h1 class="d-flex justify-content-center">Editing category</h1>

<%= render "form", category: @category %>

<div class="d-block">
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class=" b w-100 d-flex bg-primary text-white p-4 mb-2">
    <div class="text-center w-100">
      <h3 class="mb-0">CATEGORIES</h3>
    </div>

</div>
<div id="categories", class="container w-100 d-flex flex-column">
  <%if @categories.empty? %>
    <p>
      You can add categories by clicking the button
    </p>
  <%end%>
  <% @categories.each do |category| %>
    <%= link_to category_purchases_path(category),class: 'text-decoration-none text-body' do %>
      <%= render category %>
    <%end%>
  <% end %>
  <div class="container d-flex fixed-bottom justify-content-center py-2 flex-column px-2 mt-3",  style='background-color: #5fb523'>
    <%= link_to "Add Category", new_category_path, class: 'btn btn-outline-light rounded-0 py-2' %>
  </div>
  <%=render 'logout'%>
</div>

app/views/categories/new.html.erb
<div class="p-2">
  <%= render "form", category: @category %>
</div>

<p class="d-flex justify-content-center">New Category</p>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budgety</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/bac16a29bd.js" crossorigin="anonymous"></script>

  </head>

  <body>
  <div class="container vh-100 mt-md-2 px-0 px-md-2 bg-color">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-primary alert-dismissible" role="alert">
  <%= flash[:notice] %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-warning alert-dismissible" role="alert">
  <%= flash[:alert] %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/layouts/shared/_top.html.erb
<div class="fixed-top bg-blue w-100 d-flex ">
  <%= button_to  nil,:back, class:"fa fa-arrow-left"  %>
  <p><%=page_name%></p>
  <%=next_link%>
</div>

app/views/purchases/_error_messages.html.erb
<% if model.errors.any? %>
	<%model.errors.full_messages.each do |message|%>
		<p class='text-danger'><%=message%></p>
	<%end%>
<% end %>

app/views/purchases/_form.html.erb
<%= form_with scope: :purchase, url: category_purchases_path(category_id:params[:category_id]) , method: :post do |f| %>
    <div class=" b w-100 d-flex justify-content-between align-items-center bg-primary text-white">
        <%= link_to  category_purchases_path(category_id:params[:category_id]), id: 'back_to_home'  do %>
          <i class="fa fa-arrow-left text-white ms-4" aria-hidden="true"></i>
        <%end%>

      <p class="mb-0">New Purchase</p>
      <%= f.submit "Submit", class:'btn text-white btn-sm btn-success m-2 rounded-2',data:{turbo:false} %>
    </div>
          <%=render 'error_messages', model: purchase %>

        <%= f.text_field :name, placeholder: 'name', class: "form-control p-2 my-2" %>
        <%= f.text_field :amount, placeholder: 'amount', class: "form-control p-2 my-2" %>
        <%= f.select :category_id,@categories, {}, {class: "form-control form-select"}%>
<% end %>

app/views/purchases/_log_out.html.erb
<%= button_to "logout", destroy_user_session_path,method: :delete, class: 'btn btn-danger me-4 ' %>

app/views/purchases/_purchase.html.erb
<div id="<%= dom_id category %>">
  <div class="card my-1 shadow">
    <div class="container py-1 px-1">
      <div class="row">
        <div class="col-4">
          <%= image_tag category.icon, alt: category.name, style: 'width: 100px; height: 100px;' %>
        </div>
          <div class="card-body col-6">
            <div class="card-text container">
            <div class="row">
                <div class="col-6 text-secondary">
                  <h5 class=" fs-6">
                    <%=purchase.name%>
                  </h5>
                </div>
                <div class="col-6">
                  <span>$<%=purchase.amount%></span>
                </div>
                <div class="col-12 text-secondary">
                  <h6><%=purchase.updated_at.strftime("%d-%m-%y, %I:%M %P")%></h6>

                </div>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/purchases/_purchase_details.html.erb
<div id="<%= dom_id category %>">
  <div class="card my-1 shadow">
    <div class="container py-1 px-1">
      <div class="row">
        <div class='col-4'>
          <%= image_tag category.icon, alt: category.name, style: 'width: 100px; height: 100px;' %>
        </div>

        <div class="col-4 text-secondary my-3">
            <h5 class=" fs-6">
              <%=purchase.name%>
            </h5>
          </div>
      </div>

      <div class="d-flex justify-content-between py-3 px-2 text-secondary">
        <span>updated on</span>
        <span><h6><%=purchase.updated_at.strftime("%d-%m-%y")%></h6></span>
      </div>
       <div class="d-flex justify-content-between py-3 px-2 text-secondary">
        <span>time</span>
        <span><h6><%=purchase.updated_at.strftime("%I:%M %P")%></h6></span>
      </div>
      <div class="d-flex justify-content-between py-3 px-2">
          <span>Total amount</span>
          <span>$<%=purchase.amount%></span>
      </div>
    </div>

</div>

app/views/purchases/index.html.erb
<div class="p-2">
<div class=" b w-100 d-flex bg-primary text-white py-3 px-2">
    <%= link_to  categories_path(category_id: params[:category_id]) do %>
      <i class="fa fa-arrow-left text-white ms-4 mt-2" aria-hidden="true"></i>
    <%end%>
  <div class="text-center flex-grow-1">
    <H2 class="mb-0">PURCHASES</H2>
  </div>
    <%= render 'log_out'%>
</div>
<div class="d-flex justify-content-around shadow py-3 px-2 bg-white">
    <span class='text-secondary lead'>Total</span>
    <span class="lead">$<%=@total%></span>
  </div>
<div id="purchases", class="w-100 d-flex flex-column">
  <%if @purchases.empty? %>
    <p class="p-4">
      Click button to add purchase
    </p>
  <%end%>

  <% @purchases.each do |purchase| %>
    <%= link_to category_purchase_path(id:purchase.id,category_id:purchase.category.id),class: 'text-decoration-none text-body' do %>
      <%= render 'purchase',purchase:purchase,category:purchase.category %>
    <%end%>
  <% end %>
</div>
  <div class="container d-flex justify-content-center py-2 flex-column px-2 fixed-bottom",  style='background-color: #5fb523'>
    <%= link_to "Add purchase", new_category_purchase_path, class: 'btn btn-outline-light rounded-0 py-2' %>
  </div>
</div>

app/views/purchases/new.html.erb
<div class="p-2">
  <%= render "form", purchase: @purchase %>
</div>

app/views/purchases/show.html.erb
<div class=" b w-100 d-flex bg-primary text-white py-3 px-2">
    <%= link_to  category_purchases_path, id: 'back_to_purchase_home' do %>
      <i class="fa fa-arrow-left text-white" aria-hidden="true"></i>
    <%end%>
    <div class="text-center flex-grow-1">
      <p class="mb-0">Purchases Details</p>
    </div>
</div>
<p style="color: green"><%= notice %></p>

<%= render 'purchase_details', purchase: @purchase, category: @purchase.category %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-primary alert-dismissible" role="alert">
  <%= flash[:notice] %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-warning alert-dismissible" role="alert">
  <%= flash[:alert] %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/splash/index.html.erb
<div class="d-flex flex-column w-100 vh-100 container bg-light border p-2">
  <div class="h-75 text-center align-items-center justify-content-center d-flex ">
    <h1 class="splash-font">Budgety</h1>
  </div>
  <div class=" d-flex flex-column">
    <%=link_to 'Login', new_user_session_path, class: 'btn btn-primary btn-lg rounded'%>
    <%=link_to 'Sign up', new_user_registration_path, class: 'btn btn-white btn-lg text-decoration-none text-secondary text-center'%>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1 class="d-flex justify-content-center">Transactions</h1>
<div>